# Generated by Django 3.2.6 on 2021-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='surname')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='patronymic')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='login')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('photo_file', models.CharField(blank=True, max_length=255, verbose_name='photo_file')),
                ('api_token', models.CharField(blank=True, max_length=255, verbose_name='api_token')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='status')),
                ('role_id', models.BigIntegerField(verbose_name='role_id ')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
